[package]
name = "neo_mendelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13"
rust_decimal = "1.20.0"
rug = "1.14.0"
serde = "1.0.188"
serde_json = "1.0.107"
